config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  resources :control_devices
  resources :accounts
end

app/models/control_device.rb
class ControlDevice < ApplicationRecord
  validates :control_device_id, presence: true, uniqueness: true # 制御機器ID 必須　重複不可
  validates :name, presence: true, length: {maximum: 30} # 機器名 必須　文字数30
  validates :physical_code, presence: true, length: {maximum: 32} # 制御機器物理コード 必須　文字数32
  validates :is_gateway, inclusion: {in: [true, false]} # ゲートウェイフラグ 必須　文字数16
  validates :schema_id, presence: true, length: {maximum: 6} # スキーマID 必須　文字数16
end

app/controllers/control_devices_controller.rb
class ControlDevicesController < ApplicationController
  helper_method :sort_column, :sort_direction

  # 制御機器の一覧を返す。
  # @return [Object] @control_devices
  def index
    # 初回表示時には初期値の代入し、検索やソートを行った場合はパラメータを代入
    @sort_item = params[:sort_item] || "control_device_id"
    @sort_order = params[:sort_order] || "asc"
    @display_result = params[:display_result] || 50

    # @control_devicesに制御機器一覧画面で表示する値を代入
    @control_devices = if params[:search]
      ControlDevice.order("#{sort_column} #{sort_direction}")
        .where("cast(control_device_id as text) LIKE ? OR name LIKE ? OR physical_code LIKE ? OR memo LIKE ? ",
          "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%").page(params[:page]).per(@display_result)
    else
      ControlDevice.order("#{sort_column} #{sort_direction}").page(params[:page]).per(@display_result)
    end

    # CSVダウンロード処理
    respond_to do |format|
      format.html
      format.csv do
        filename = "制御機器一覧.csv" # ファイル名指定
        send_data render_to_string, filename: filename, type: :csv
      end
    end
  end

  # 参照する制御機器情報を返す。
  # @return [Object] @control_device
  def show
    @control_device = ControlDevice.find(params[:id])
  end

  # 制御機器を新規作成して返す。
  # @return [Object] @control_device
  def new
    @control_device = ControlDevice.new
  end

  # 新規作成の制御機器を保存する。
  def create
    @control_device = ControlDevice.new(control_device_params)
    # 制御機器IDは１から連番。最大値を取得して代入？
    @control_device.control_device_id = if ControlDevice.maximum(:control_device_id).nil?
      1
    else
      ControlDevice.maximum(:control_device_id) + 1
    end
    # control_device_paramsから制御機器を新規作成する
    if @control_device.save
      # 操作履歴の保存　※grp_id,handle_idは仮
      save_history(1, 1, "制御機器を登録しました")
      flash[:success] = "制御機器は正常に新規作成されました"
      redirect_to new_control_device_path
    else
      render :new
    end
  end

  # 編集する制御機器の情報を返す。
  # @return [Object] @control_device
  def edit
    @control_device = ControlDevice.find(params[:id])
  end

  # 制御機器情報を更新する。
  def update
    @control_device = ControlDevice.find(params[:id])

    if @control_device.update(control_device_params)
      # 操作履歴の保存　※grp_id,handle_idは仮
      save_history(1, 1, "制御機器を編集しました")
      flash[:success] = "制御機器は正常に更新されました"
      redirect_to edit_control_device_path
    else
      render :edit
    end
  end

  # 制御機器を削除する。
  def destroy
    @control_device = ControlDevice.find(params[:id])
    @control_device.destroy

    # 操作履歴の保存　※grp_id,handle_idは仮
    save_history(1, 1, "制御機器を削除しました")
    flash[:success] = "制御機器は正常に削除されました"
    redirect_to control_devices_url
  end

  private

  # 指定したパスワードで認証を行う。
  # @return [Object] @control_devices 制御機器一覧画面で表示するリスト
  def control_device_params
    params.require(:control_device).permit(:control_device_id, :name, :physical_code, :is_gateway, :schema_id, :memo)
  end

  # 指定したパスワードで認証を行う。
  # @return [Object] @control_devices 制御機器一覧画面で表示するリスト
  def sort_direction
    %w[asc desc].include?(params[:sort_item]) ? params[:sort_item] : @sort_order
  end

  # 指定したパスワードで認証を行う。
  # @return [Object] @control_devices 制御機器一覧画面で表示するリスト
  def sort_column
    ControlDevice.column_names.include?(params[:sort]) ? params[:sort] : @sort_item
  end
end

app/helpers/control_devices_helper.rb
module ControlDevicesHelper
end

app/views/control_devices/edit.html.erb
<h1>制御機器管理 - 編集</h1>

<%= flash[:success] %>

<h2>制御機器情報</h2>

<% if @control_device.errors.any? %>
  <div class = "alert">
    <ul>
      <% @control_device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @control_device, local: true) do |f| %>
    <%= f.label :control_device_id, '制御機器ID（必須）' %>
    <%= f.text_field :control_device_id, value: @control_device.control_device_id, readonly: true %>
    <%= f.label :name, '名称（必須）' %>
    <%= f.text_field :name, value: @control_device.name%>
    <%= f.label :physical_code, '制御機器物理コード（必須）' %>
    <%= f.text_field :physical_code, value: @control_device.physical_code, readonly: true%>
    <%= f.label :is_gateway, 'ゲートウェイフラグ（必須）' %>
    <%= f.check_box :is_gateway, value: @control_device.is_gateway%>
    <%= f.label :schema_id, 'スキーマID（必須）' %>
    <%= f.text_field :schema_id, value: @control_device.schema_id, readonly: true%>
    <%= f.label :memo, 'メモ' %>
    <%= f.text_field :memo, value: @control_device.memo%>
    <%= f.submit '更新' , data: { confirm: '本当に更新してよろしいですか？'}%>
<% end %>

<%=link_to(control_devices_path) do %>
    <button>一覧に戻る</button>
<%end%>

<%= button_to  '削除', @control_device, method: :delete, data: { confirm: '本当に削除してよろしいですか？'}%>

app/views/control_devices/index.html.erb
<h1>制御機器管理 - 一覧</h1>

<%=link_to(new_control_device_path) do %>
    <button>新規登録</button>
<%end%>

<%= form_with url: control_devices_url , method: :get, local: true do  |form| %>
  <%= form.text_field :search, autofocus: true, maxlength: "18"  %>
  <%= form.submit '検索' %>
<% end %>

<%= paginate @control_devices %>

<%=link_to(control_devices_url(display_result: 10)) do %>
    <button>10件表示</button>
<%end%>

<%=link_to(control_devices_url(display_result: 50)) do %>
    <button>50件表示</button>
<%end%>
 

<% if @control_devices.empty? %>
    <p>"検索ワード"に一致するものはありませんでした</p>
<%else%>
    <table border=”1″>
        <tr>
            <th>制御機器ID<%= sort_asc("control_device_id")%><%= sort_desc("control_device_id")%></th>
            <th>名称<%= sort_asc("name")%><%= sort_desc("name")%></th>
            <th>制御機器物理コード<%= sort_asc("physical_code")%><%= sort_desc("physical_code")%></th>
            <th>メモ<%= sort_asc("memo")%><%= sort_desc("memo")%></th>
        </tr>
        <% @control_devices.each do |control_device| %>
            <tr>
                <td><%= link_to control_device.control_device_id, control_device %></td>
                <td><%= control_device.name %></td>
                <td><%= control_device.physical_code %></td>
                <td><%= control_device.memo %></td>
            </tr>
        <% end %>
    </table>
<%end%>

<%= paginate @control_devices %>

<%=link_to(control_devices_url(format: :csv)) do %>
    <button>CSVダウンロード</button>
<%end%>

app/views/control_devices/new.html.erb
<h1>アカウント管理 - 新規登録</h1>

<%= flash[:success] %>

<% if @control_device.errors.any? %>
  <div class = "alert">
    <ul>
      <% @control_device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @control_device, local: true) do |f| %>
    <%= f.label :name, '名称（必須）' %>
    <%= f.text_field :name %>
    <%= f.label :physical_code, '制御機器物理コード（必須）' %>
    <%= f.text_field :physical_code %>
    <%= f.label :is_gateway, 'ゲートウェイフラグ（必須）' %>
    <%= f.check_box :is_gateway %>
    <%= f.label :schema_id, 'スキーマID（必須）' %>
    <%= f.text_field :schema_id %>
    <%= f.label :memo, 'メモ' %>
    <%= f.text_field :memo %>
    <%= f.submit '登録' , data: { confirm: '本当に登録してよろしいですか？'}%>
<% end %>

<%=link_to(control_devices_path) do %>
    <button>一覧に戻る</button>
<%end%>

app/views/control_devices/show.html.erb
<h1>制御機器管理 - 参照</h1>

<%= flash[:success] %>

<h2>制御機器情報</h2>

<%= form_with(model: @control_device, local: true) do |f| %>
    <%= f.label :control_device_id, '制御機器ID（必須）' %>
    <%= f.text_field :control_device_id, value: @control_device.control_device_id, disabled: true %>
    <%= f.label :name, '名称（必須）' %>
    <%= f.text_field :name, value: @control_device.name , disabled: true  %>
    <%= f.label :physical_code, '制御機器物理コード（必須）' %>
    <%= f.text_field :physical_code, value: @control_device.physical_code, disabled: true%>
    <%= f.label :is_gateway, 'ゲートウェイフラグ（必須）' %>
    <%= f.check_box :is_gateway, value: @control_device.is_gateway, disabled: true%>
    <%= f.label :schema_id, 'スキーマID（必須）' %>
    <%= f.text_field :schema_id, value: @control_device.schema_id, disabled: true%>
    <%= f.label :memo, 'メモ' %>
    <%= f.text_field :memo, value: @control_device.memo, disabled: true%>
<% end %>

<%=link_to(control_devices_path) do %>
    <button>一覧に戻る</button>
<%end%>

<%=link_to(edit_control_device_path) do %>
    <button>編集</button>
<%end%>