config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  resources :control_devices
  resources :accounts
end

app/models/account.rb
class Account < ApplicationRecord
  validates :account_id, presence: true, uniqueness: true # アカウントID 必須　重複不可
  validates :account_code, presence: true, length: {maximum: 32} # アカウントコード 必須　文字数32
  validates :mail_address, presence: true, length: {maximum: 129}, format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i} # メールアドレス 必須　文字数129 フォーマット指定
  has_secure_password
  validates :password, presence: true, length: {maximum: 60}, confirmation: true # パスワード 必須　文字数60　確認照合 ハッシュ
  validates :family_name, presence: true, length: {maximum: 16} # 姓 必須　文字数16
  validates :first_name, presence: true, length: {maximum: 16} # 名 必須　文字数16
  validates :kana_family_name, length: {maximum: 16} # かな姓 必須　文字数16
  validates :kana_first_name, length: {maximum: 16} # かな名 必須　文字数16
  validates :birth, format: {with: /\A\d{4}-\d{2}-\d{2}\z/} # 生年月日 必須　文字数16
  validates :valid_start_date, format: {with: /\A\d{4}-\d{2}-\d{2}\z/} # 有効開始日 必須　文字数16
  validates :valid_end_date, format: {with: /\A\d{4}-\d{2}-\d{2}\z/} # 終了日 必須　文字数16
  validates :is_valid, inclusion: {in: [true, false]} # 有効フラグ 必須　文字数16
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  helper_method :sort_column, :sort_direction

  # アカウントの一覧を返す。
  # @return [Object] @accounts
  def index
    # 初回表示時には初期値の代入し、検索やソートを行った場合はパラメータを代入
    @sort_item = params[:sort_item] || "account_id"
    @sort_order = params[:sort_order] || "asc"
    @display_result = params[:display_result] || 50

    # @accountsにアカウント一覧画面で表示する値を代入
    @accounts = if params[:search]
      Account.order("#{sort_column} #{sort_direction}")
        .where("cast(account_id as text) LIKE ? OR account_code LIKE ? OR mail_address LIKE ? OR memo LIKE ? OR cast(created_at as text) LIKE ? OR cast(updated_at as text) LIKE ?",
          "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%").page(params[:page]).per(@display_result)
    else
      Account.order("#{sort_column} #{sort_direction}").page(params[:page]).per(@display_result)
    end

    # CSVダウンロード処理
    respond_to do |format|
      format.html
      format.csv do
        filename = "アカウント一覧.csv" # ファイル名指定
        send_data render_to_string, filename: filename, type: :csv
      end
    end
  end

  # 参照するアカウント情報を返す。
  # @return [Object] @account
  def show
    @account = Account.find(params[:id])
  end

  # アカウントを新規作成して返す。
  # @return [Object] @account
  def new
    @account = Account.new
  end

  # 新規作成のアカウントを保存する。
  def create
    @account = Account.new(account_params)
    # アカウントIDは１から連番。最大値を取得して代入？
    @account.account_id = if Account.maximum(:account_id).nil?
      1
    else
      Account.maximum(:account_id) + 1
    end
    # account_paramsからアカウントを新規作成する
    if @account.save
      # 操作履歴の保存　※grp_id,handle_idは仮
      save_history(1, 1, "アカウントを登録しました")
      flash[:success] = "アカウントは正常に新規作成されました"
      redirect_to new_account_path
    else
      render :new
    end
  end

  # 編集するアカウントの情報を返す。
  # @return [Object] @account
  def edit
    @account = Account.find(params[:id])
  end

  # アカウント情報を更新する。
  def update
    @account = Account.find(params[:id])
    if @account.update(account_params)
      # 操作履歴の保存　※grp_id,handle_idは仮
      save_history(1, 1, "アカウントを編集しました")
      flash[:success] = "アカウントは正常に更新されました"
      redirect_to edit_account_path
    else
      render :edit
    end
  end

  # アカウントを削除する。
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    # 操作履歴の保存　※grp_id,handle_idは仮
    save_history(1, 1, "アカウントを削除しました")
    flash[:success] = "アカウントは正常に削除されました"
    redirect_to accounts_url
  end

  private

  # 指定したパスワードで認証を行う。
  # @return [Object] @accounts アカウント一覧画面で表示するリスト
  def account_params
    params.require(:account).permit(:account_id, :account_code, :mail_address, :password, :password_confirmation, :family_name, :first_name, :kana_family_name, :kana_first_name, :birth, :valid_start_date, :valid_end_date, :is_valid, :memo, :created_at, :updated_at)
  end

  # 指定したパスワードで認証を行う。
  # @return [Object] @accounts アカウント一覧画面で表示するリスト
  def sort_direction
    %w[asc desc].include?(params[:sort_item]) ? params[:sort_item] : @sort_order
  end

  # 指定したパスワードで認証を行う。
  # @return [Object] @accounts アカウント一覧画面で表示するリスト
  def sort_column
    Account.column_names.include?(params[:sort]) ? params[:sort] : @sort_item
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/edit.html.erb
<h1>アカウント管理 - 編集</h1>

<%= flash[:success] %>

<h2>アカウント情報</h2>

<% if @account.errors.any? %>
  <div class = "alert">
    <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @account, local: true) do |f| %>
    <%= f.label :account_id, 'アカウントID（必須）' %>
    <%= f.text_field :account_id, value: @account.account_id , readonly: true  %>
    <%= f.label :account_code, 'アカウントコード（必須）' %>
    <%= f.text_field :account_code, value: @account.account_code%>
    <%= f.label :mail_address, 'メールアドレス（必須）' %>
    <%= f.text_field :mail_address, value: @account.mail_address%>
    <%= f.label :password, 'パスワード（必須）' %>
    <%= f.password_field :password%>
    <%= f.label :password_confirmation, 'パスワード確認（必須）' %>
    <%= f.password_field :password_confirmation%>
    <%= f.label :family_name, '姓（必須）' %>
    <%= f.text_field :family_name, value: @account.family_name%>
    <%= f.label :first_name, '名（必須）' %>
    <%= f.text_field :first_name, value: @account.first_name%>
    <%= f.label :kana_family_name, 'かな姓（必須）' %>
    <%= f.text_field :kana_family_name, value: @account.kana_family_name%>
    <%= f.label :kana_first_name, 'かな名（必須）' %>
    <%= f.text_field :kana_first_name, value: @account.kana_first_name%>
    <%= f.label :birth, '生年月日（必須）' %>
    <%= f.text_field :birth, value: @account.birth%>
    <%= f.label :valid_start_date, '有効開始日（必須）' %>
    <%= f.text_field :valid_start_date, value: @account.valid_start_date%>
    <%= f.label :valid_end_date, '終了日' %>
    <%= f.text_field :valid_end_date, value: @account.valid_end_date%>
    <%= f.label :is_valid, '有効フラグ（必須）' %>
    <%= f.check_box :is_valid, value: @account.is_valid%>
    <%= f.label :memo, 'メモ' %>
    <%= f.text_field :memo, value: @account.memo%>
    <%= f.submit '更新' , data: { confirm: '本当に更新してよろしいですか？'}%>
<% end %>

<%=link_to(accounts_path) do %>
    <button>一覧へ戻る</button>
<%end%>

<%= button_to  '削除', @control_device, method: :delete, data: { confirm: '本当に削除してよろしいですか？'}%>

app/views/accounts/index.html.erb
<h1>アカウント管理 - 一覧</h1>

<%=link_to(new_account_path) do %>
    <button>新規登録</button>
<%end%>

<%= form_with url: accounts_url , method: :get, local: true do  |form| %>
  <%= form.text_field :search, autofocus: true, maxlength: "18"  %>
  <%= form.submit '検索' %>
<% end %>

<%= paginate @accounts %>

<%=link_to(accounts_url(display_result: 10)) do %>
    <button>10件表示</button>
<%end%>

<%=link_to(accounts_url(display_result: 50)) do %>
    <button>50件表示</button>
<%end%>
 

<% if @accounts.empty? %>
    <p>"検索ワード"に一致するものはありませんでした</p>
<%else%>
    <table border=”1″>
        <tr>
            <th>アカウントID<%= sort_asc("account_id")%><%= sort_desc("account_id")%></th>
            <th>アカウントコード<%= sort_asc("account_code")%><%= sort_desc("account_code")%></th>
            <th>メールアドレス<%= sort_asc("mail_address")%><%= sort_desc("mail_address")%></th>
            <th>メモ<%= sort_asc("memo")%><%= sort_desc("memo")%></th>
            <th>作成日<%= sort_asc("created_at")%><%= sort_desc("created_at")%></th>
            <th>最終更新日<%= sort_asc("updated_at")%><%= sort_desc("updated_at")%></th>
        </tr>
        <% @accounts.each do |account| %>
            <tr>
                <td><%= link_to account.account_id, account %></span></td>
                <td><%= account.account_code %></td>
                <td><%= account.mail_address %></td>
                <td><%= account.memo %></td>
                <td><%= account.created_at.to_s(:datetime_jp) %></td>
                <td><%= account.updated_at.to_s(:datetime_jp) %></td>
            </tr>
        <% end %>
    </table>
<%end%>

<%= paginate @accounts %>

<%=link_to(accounts_url(format: :csv)) do %>
    <button>CSVダウンロード</button>
<%end%>

app/views/accounts/new.html.erb
<h1>アカウント管理 - 新規登録</h1>

<%= flash[:success] %>

<% if @account.errors.any? %>
  <div class = "alert">
    <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @account, local: true) do |f| %>
    <%= f.label :account_code, 'アカウントコード（必須）' %>
    <%= f.text_field :account_code %>
    <%= f.label :mail_address, 'メールアドレス（必須）' %>
    <%= f.text_field :mail_address %>
    <%= f.label :password, 'パスワード（必須）' %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation, 'パスワード確認（必須）' %>
    <%= f.password_field :password_confirmation%>
    <%= f.label :family_name, '姓（必須）' %>
    <%= f.text_field :family_name %>
    <%= f.label :first_name, '名（必須）' %>
    <%= f.text_field :first_name %>
    <%= f.label :kana_family_name, 'かな姓（必須）' %>
    <%= f.text_field :kana_family_name %>
    <%= f.label :kana_first_name, 'かな名（必須）' %>
    <%= f.text_field :kana_first_name %>
    <%= f.label :birth, '生年月日（必須）' %>
    <%= f.date_select(
          :birth,
          start_year: 1900,
          end_year: (Time.now.year),
          default: Date.new(2000, 1, 1)) %>
    <%= f.label :valid_start_date, '有効開始日（必須）' %>
    <%= f.text_field :valid_start_date %>
    <%= f.label :valid_end_date, '終了日' %>
    <%= f.text_field :valid_end_date %>
    <%= f.label :is_valid, '有効フラグ（必須）' %>
    <%= f.check_box :is_valid %>
    <%= f.label :memo, 'メモ' %>
    <%= f.text_field :memo %>
    <%= f.submit '登録' , data: { confirm: '本当に登録してよろしいですか？'}%>
<% end %>

<%=link_to(accounts_path) do %>
    <button>一覧に戻る</button>
<%end%>

app/views/accounts/show.html.erb
<h1>アカウント管理 - 参照</h1>

<h2>アカウント情報</h2>

<%= form_with(model: @account, local: true) do |f| %>
    <%= f.label :account_id, 'アカウントID' %>
    <%= f.text_field :account_id, value: @account.account_id, disabled: true %>
    <%= f.label :account_code, 'アカウントコード' %>
    <%= f.text_field :account_code, value: @account.account_code, disabled: true %>
    <%= f.label :mail_address, 'メールアドレス' %>
    <%= f.text_field :mail_address, value: @account.mail_address, disabled: true %>
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password, disabled: true %>
    <%= f.label :family_name, '姓' %>
    <%= f.text_field :family_name, value: @account.family_name, disabled: true %>
    <%= f.label :first_name, '名' %>
    <%= f.text_field :first_name, value: @account.first_name, disabled: true %>
    <%= f.label :kana_family_name, 'かな姓' %>
    <%= f.text_field :kana_family_name, value: @account.kana_family_name, disabled: true %>
    <%= f.label :kana_first_name, 'かな名' %>
    <%= f.text_field :kana_first_name, value: @account.kana_first_name, disabled: true %>
    <%= f.label :birth, '生年月日' %>
    <%= f.text_field :birth, value: @account.birth, disabled: true %>
    <%= f.label :valid_start_date, '有効開始日' %>
    <%= f.text_field :valid_start_date, value: @account.valid_start_date, disabled: true %>
    <%= f.label :valid_end_date, '終了日' %>
    <%= f.text_field :valid_end_date, value: @account.valid_end_date, disabled: true %>
    <%= f.label :is_valid, '有効フラグ' %>
    <%= f.check_box :is_valid, value: @account.is_valid, disabled: true %>
    <%= f.label :memo, 'メモ' %>
    <%= f.text_field :memo, value: @account.memo, disabled: true %>
<% end %>

<%=link_to(accounts_path) do %>
    <button>一覧に戻る</button>
<%end%>

<%=link_to(edit_account_path) do %>
    <button>編集</button>
<%end%>